// <auto-generated />
using System;
using EF_Day2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Day2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepartmentProject", b =>
                {
                    b.Property<int>("Departmentsid")
                        .HasColumnType("int");

                    b.Property<byte>("ProjectSsN")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProjectsName")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Departmentsid", "ProjectSsN", "ProjectsName");

                    b.HasIndex("ProjectSsN", "ProjectsName");

                    b.ToTable("DepartmentProject");
                });

            modelBuilder.Entity("EF_Day2.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("Managerssn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Managerssn");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EF_Day2.Models.Employee", b =>
                {
                    b.Property<int>("ssn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ssn"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SuperId")
                        .HasColumnType("int");

                    b.HasKey("ssn");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SuperId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EF_Day2.Models.Project", b =>
                {
                    b.Property<byte>("ProjectSsN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ProjectSsN"));

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ProjectN");

                    b.HasKey("ProjectSsN", "Name");

                    b.ToTable("Projects", "Prod");
                });

            modelBuilder.Entity("DepartmentProject", b =>
                {
                    b.HasOne("EF_Day2.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("Departmentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Day2.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectSsN", "ProjectsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF_Day2.Models.Department", b =>
                {
                    b.HasOne("EF_Day2.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("Managerssn");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EF_Day2.Models.Employee", b =>
                {
                    b.HasOne("EF_Day2.Models.Department", "department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EF_Day2.Models.Employee", "Super")
                        .WithMany("emps")
                        .HasForeignKey("SuperId");

                    b.Navigation("Super");

                    b.Navigation("department");
                });

            modelBuilder.Entity("EF_Day2.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EF_Day2.Models.Employee", b =>
                {
                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
